export * as face from "./face"
export * as tetra from "./tetra"
export { FaceMesh, FaceIndexMesh } from "./face/facemesh"
export { TetraMesh, TetraIndexMesh } from "./tetra/tetramesh"
export type { FaceMeshData, FaceIndexMeshData } from "./face/facemesh"
export type { TetraMeshData, TetraIndexMeshData } from "./tetra/tetramesh"
export * from "./objparser"